import { test, expect } from '@playwright/test'
import { createHash } from 'node:crypto'
import { readFile, writeFile, readdir } from 'node:fs/promises'
import { promisify } from 'node:util'
import { execFile } from 'node:child_process'

test('artefacto real conserva bytes y muestra huella, versión y límites', async ({ page }, testInfo) => {
  const user = JSON.parse(await readFile(new URL('../.playwright-fixture/user.json', import.meta.url), 'utf8'))
  const { workspace } = JSON.parse(await readFile(new URL('../.playwright-fixture/workspace.json', import.meta.url), 'utf8'))
  const id = 'artifact-fingerprint'
  await page.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:4199' ? route.continue() : route.abort())
  await page.goto('/')
  await page.getByLabel('Contraseña').fill(user.password)
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Cerrar sesión', exact: true })).toBeVisible()
  expect((await page.request.post('/api/v1/engagements', { data: { name: id, domain: 'example.test', type: 'engagement' } })).ok()).toBe(true)
  const path = `${workspace}/engagements/${id}/recon/raw.txt`
  const raw = Buffer.from('<script>fixture-only</script>\nRespuesta sintética: á\n')
  await writeFile(path, raw)
  await page.goto(`/engagements/engagement/${id}`)
  await page.getByRole('button', { name: /Artefactos \(recon\/\)/ }).click()
  const file = page.getByRole('button', { name: /raw.txt/ })
  await file.click()
  const metadata = page.getByTestId('artifact-fingerprint')
  const sha = createHash('sha256').update(raw).digest('hex')
  await expect(metadata).toContainText(sha)
  await expect(metadata).toContainText(`${raw.length} bytes`)
  await expect(metadata).toContainText('no acredita procedencia')
  await expect(page.locator('pre').filter({ hasText: 'fixture-only' })).toHaveText(raw.toString())
  await expect(page.locator('script').filter({ hasText: 'fixture-only' })).toHaveCount(0)
  expect(await readFile(path)).toEqual(raw)
  await page.screenshot({ path: testInfo.outputPath('artifact-fingerprint.png'), fullPage: true })
  const changed = Buffer.from('Versión diferente\n')
  await writeFile(path, changed)
  await file.click()
  await expect(metadata).toContainText(createHash('sha256').update(changed).digest('hex'))
  await expect(metadata).not.toContainText(sha)
  const large = Buffer.alloc(2 * 1024 * 1024 + 1, 'a')
  await writeFile(path, large)
  await file.click()
  await expect(metadata).toContainText(createHash('sha256').update(large).digest('hex'))
  await expect(metadata).toContainText('supera 2 MiB')
  await expect(page.getByRole('button', { name: 'Copiar Previsualización', exact: true })).toBeDisabled()
  const original = await readFile(path)
  expect(original).toEqual(large)
  expect(await readdir(`${workspace}/engagements/${id}/recon`)).toEqual(['raw.txt'])
  const missing = await page.request.get(`/api/v1/loot/${id}/artifacts/content`, { params: { path: '../other/secret' } })
  expect(missing.status()).toBe(404)
  await writeFile(path, raw)
  const created = await page.request.post(`/api/v1/findings/${id}`, { data: { slug: 'linked', title: 'Hallazgo sintético vinculado', asset: 'example.test', status: 'CANDIDATE' } })
  expect(created.ok()).toBe(true)
  await page.reload()
  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await page.getByRole('button', { name: 'Editar', exact: true }).click()
  const editor = page.getByTestId('finding-artifact-editor')
  await page.getByLabel('Ruta del artefacto', { exact: true }).fill('recon/raw.txt')
  await page.getByRole('button', { name: 'Revisar artefacto', exact: true }).click()
  await expect(editor).toContainText(sha)
  await page.getByRole('button', { name: 'Vincular versión revisada', exact: true }).click()
  await page.getByRole('button', { name: 'Guardar Ficha', exact: true }).click()
  const linked = page.getByTestId('finding-artifact-ref')
  await expect(linked).toContainText(sha)
  await page.reload()
  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await expect(linked).toContainText(sha)
  const report = await (await page.request.post(`/api/v1/reports/${id}/compile`)).json()
  expect(report.success, report.log).toBe(true)
  expect(report.content).toContain(sha)
  expect(report.content).toContain('**0 hallazgos confirmados activos**')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /Empaquetar y Descargar/ }).click()
  const download = await downloadPromise
  const archive = testInfo.outputPath('linked-evidence.tar.gz')
  await download.saveAs(archive)
  const run = promisify(execFile)
  const { stdout: manifest } = await run('tar', ['-xOf', archive, `${id}/source-manifest.json`])
  const row = JSON.parse(manifest).files.find(row => row.path === 'recon/raw.txt')
  expect(row.original_sha256).toBe(sha)
  const { stdout: copied } = await run('tar', ['-xOf', archive, `${id}/recon/raw.txt`])
  expect(createHash('sha256').update(copied).digest('hex')).toBe(row.export_sha256)
  expect(await readFile(path)).toEqual(raw)
  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await page.getByRole('button', { name: 'Abrir recon/raw.txt', exact: true }).click()
  await expect(metadata).toContainText(sha)
  await writeFile(path, changed)
  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await page.getByRole('button', { name: 'Abrir recon/raw.txt', exact: true }).click()
  await expect(metadata).toContainText('no coincide con la vinculada')
  await page.screenshot({ path: testInfo.outputPath('linked-artifact-changed.png'), fullPage: true })
  const blockedReport = await (await page.request.post(`/api/v1/reports/${id}/compile`)).json()
  expect(blockedReport.success).toBe(false)
  expect((await page.request.get(`/api/v1/reports/${id}/download`)).status()).toBe(409)
})
