import { test, expect } from '@playwright/test'
import { createHash } from 'node:crypto'
import { promisify } from 'node:util'
import { execFile } from 'node:child_process'
import { readFile, writeFile } from 'node:fs/promises'

async function json(response) {
  expect(response.ok()).toBe(true)
  return response.json()
}

async function compile(page, id) {
  const response = page.waitForResponse(r => r.url().includes(`/reports/${id}/compile`) && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Compilar Reporte', exact: false }).first().click()
  const result = await json(await response)
  expect(result.success, result.log).toBe(true)
  return result.content
}

test('auditoría sintética: alcance, simulación, bloqueo, evidencia y reporte', async ({ page }, testInfo) => {
  test.setTimeout(90000)
  const user = JSON.parse(await readFile(new URL('../.playwright-fixture/user.json', import.meta.url), 'utf8'))
  const run = promisify(execFile)
  const { workspace, container } = JSON.parse(await readFile(new URL('../.playwright-fixture/workspace.json', import.meta.url), 'utf8'))
  const { stdout: network } = await run('docker', ['inspect', '--format', '{{.HostConfig.NetworkMode}}', container])
  expect(network.trim()).toBe('none')
  const id = 'playwright-audit'
  const title = 'Evidencia sintética de acceso a perfil'
  await page.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:4199' ? route.continue() : route.abort())
  await page.goto('/wizard')
  await page.getByLabel('Contraseña').fill(user.password)
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await page.getByPlaceholder('acme-corp', { exact: true }).fill(id)
  await page.getByPlaceholder('target.local', { exact: true }).fill('example.test')
  await page.getByRole('button', { name: 'Crear y continuar →' }).click()
  await expect(page.getByRole('button', { name: 'Guardar y continuar →' })).toBeDisabled()
  await expect(page.getByPlaceholder('target.local\n*.target.local')).toHaveValue('example.test')
  await page.getByTestId('confirm-scope').check()
  await page.getByRole('button', { name: 'Guardar y continuar →' }).click()
  const dryRun = page.getByRole('checkbox', { name: /Modo Dry-Run/ })
  await expect(dryRun).toBeChecked()
  await dryRun.uncheck()
  await expect(page.getByRole('button', { name: /Lanzar reconocimiento/ })).toBeDisabled()
  await dryRun.check()
  await page.getByRole('button', { name: /Lanzar reconocimiento/ }).click()
  await expect(page).toHaveURL(new RegExp(`/engagements/engagement/${id}$`))
  const scope = await json(await page.request.get(`/api/v1/scope/${id}`))
  expect(scope.scope.in_scope.domains).toEqual(['example.test'])
  expect(scope.authorization.allow_active).toBe(false)
  expect(scope.authorization.allow_passive).toBe(false)
  await page.getByRole('button', { name: /Reconocimiento/, exact: false }).filter({ hasText: '📡' }).click()
  await expect(page.getByText('Simulación finalizada sin consultas de red.', { exact: false })).toBeVisible({ timeout: 20000 })
  const simulated = await json(await page.request.get(`/api/v1/recon/${id}/status`))
  expect(simulated.job.status).toBe('simulated')
  expect(simulated.summary.subdomains_count).toBe(0)
  const history = page.getByTestId('recon-history')
  await expect(history.getByRole('listitem')).toHaveCount(1)
  await expect(history).toContainText(simulated.job.run_id)

  await page.getByRole('button', { name: /Alcance \(target.yaml\)/ }).click()
  await page.getByLabel('Referencia de autorización').fill('Fixture sintético Playwright; sin permiso activo')
  await page.getByLabel('Inicio', { exact: true }).fill('2020-01-01T00:00')
  await page.getByLabel('Fin', { exact: true }).fill('2099-01-01T00:00')
  const saved = page.waitForResponse(r => r.url().includes(`/scope/${id}`) && r.request().method() === 'PUT')
  await page.getByRole('button', { name: 'Guardar Alcance' }).click()
  await json(await saved)
  await page.getByRole('button', { name: /Reconocimiento/ }).filter({ hasText: '📡' }).click()
  await writeFile(`${workspace}/engagements/${id}/recon/subdomains.txt`, 'example.test\n')
  await page.locator('select').selectOption('probe')
  await page.getByLabel('Modo Dry-Run (Simulación)').uncheck()
  await page.getByRole('button', { name: /Iniciar Reconocimiento/ }).click()
  await expect(page.getByText('Reconocimiento bloqueado por Scope Guard.', { exact: true })).toBeVisible({ timeout: 20000 })
  const blocked = await json(await page.request.get(`/api/v1/recon/${id}/status`))
  expect(blocked.job.status).toBe('blocked')
  expect(blocked.job.error).toMatch(/activ/i)
  expect(blocked.job.run_id).not.toBe(simulated.job.run_id)
  await expect(history.getByRole('listitem')).toHaveCount(2)
  await page.reload()
  await page.getByRole('button', { name: /Reconocimiento/ }).filter({ hasText: '📡' }).click()
  await expect(history.getByRole('listitem')).toHaveCount(2)
  await expect(history).toContainText(simulated.job.run_id)
  await expect(history).toContainText(blocked.job.run_id)
  await expect(history).toContainText('Bloqueado (Scope Guard)')

  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await page.getByRole('button', { name: /Nueva Ficha/ }).click()
  const form = page.locator('form').filter({ has: page.getByPlaceholder('idor-user-profile, sqli-login') })
  await expect(form.locator('select').first()).toHaveValue('CANDIDATE')
  await page.getByPlaceholder('idor-user-profile, sqli-login').fill('synthetic-profile')
  await page.getByPlaceholder('api.target.local/v1/profile').fill('https://example.test/profile')
  await page.getByPlaceholder('Insecure Direct Object Reference (IDOR) en Actualización de Cuenta').fill(title)
  await page.getByPlaceholder('Explicación detallada del fallo y cómo fue detectado...').fill('Fixture sintético, no prueba sobre un objetivo real.')
  await page.getByPlaceholder('1. Realizar petición POST', { exact: false }).fill('1. Revisar la petición sintética.\n2. Comparar la respuesta y el control negativo sintéticos.')
  await page.getByPlaceholder('GET /api/user/102', { exact: false }).fill('GET /profile HTTP/1.1\nHost: example.test')
  await page.getByPlaceholder('HTTP/1.1 200 OK', { exact: false }).fill('HTTP/1.1 200 OK\nContent-Type: application/json\n\n{"fixture":true}')
  await page.getByPlaceholder('Implementar validación', { exact: false }).fill('Revisar acceso por objeto; ejemplo sintético.')
  await page.getByRole('button', { name: 'Guardar Ficha', exact: true }).click()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  const candidate = (await json(await page.request.get(`/api/v1/findings/${id}`)))[0]
  expect(candidate.frontmatter.status).toBe('CANDIDATE')
  expect(candidate.body).toContain('Host: example.test')
  const candidateReport = await compile(page, id)
  expect(candidateReport).toContain('**0 hallazgos confirmados activos**')
  expect(candidateReport).toContain(title)
  await expect(page.locator('.report-printable div.text-center span.text-2xl')).toHaveText(['0', '0', '0', '0', '0'])
  await expect(page.locator('.report-printable')).toContainText('BORRADOR / PENDIENTE DE REVISIÓN')

  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await page.getByRole('button', { name: 'Editar', exact: true }).click()
  await expect(page.getByTestId('finding-markdown')).toHaveValue(candidate.body)
  await form.locator('select').first().selectOption('PROVEN')
  await page.getByTestId('finding-markdown').fill(`${candidate.body}\n## Control negativo\nHTTP/1.1 403 Forbidden; respuesta sintética sin credencial.\n\n## Revisión\nOperador del fixture revisó petición, respuesta y control sintéticos; no acredita una prueba real.`)
  await page.getByRole('button', { name: 'Guardar Ficha', exact: true }).click()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  const confirmedReport = await compile(page, id)
  expect(confirmedReport).toContain('**1 hallazgos confirmados activos**')
  expect(confirmedReport).toContain('HTTP/1.1 403 Forbidden')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /Empaquetar y Descargar/ }).click()
  const download = await downloadPromise
  const archive = testInfo.outputPath('synthetic-audit.tar.gz')
  await download.saveAs(archive)
  expect(await download.failure()).toBeNull()
  const { stdout: entries } = await run('tar', ['-tf', archive])
  const manifestPath = entries.split('\n').find(path => path.endsWith('/source-manifest.json'))
  expect(manifestPath).toBeTruthy()
  const { stdout: manifestText } = await run('tar', ['-xOf', archive, manifestPath])
  const manifest = JSON.parse(manifestText)
  expect(manifest.schema_version).toBe(1)
  expect(manifest.sanitized).toBe(true)
  expect(manifest.files.map(file => file.path)).toEqual(expect.arrayContaining(['REPORT.md', 'target.yaml', 'evidence/synthetic-profile.md', 'recon/subdomains.txt']))
  for (const file of manifest.files) {
    expect(file.original_sha256).toMatch(/^[a-f0-9]{64}$/)
    expect(file.export_sha256).toMatch(/^[a-f0-9]{64}$/)
    const exportedPath = entries.split('\n').find(path => path.endsWith(`/${file.path}`))
    expect(exportedPath).toBeTruthy()
    const { stdout: exported } = await run('tar', ['-xOf', archive, exportedPath], { encoding: 'buffer' })
    expect(createHash('sha256').update(exported).digest('hex')).toBe(file.export_sha256)
    const original = await readFile(`${workspace}/engagements/${id}/${file.path}`)
    expect(createHash('sha256').update(original).digest('hex')).toBe(file.original_sha256)
  }
  await page.reload()
  await page.getByRole('button', { name: /Reporte \(REPORT.md\)/ }).click()
  await page.getByRole('button', { name: /Markdown/ }).click()
  await expect(page.locator('pre').filter({ hasText: '# Informe de Auditoría' })).toContainText(confirmedReport.trim())

  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await page.getByRole('button', { name: 'Editar', exact: true }).click()
  await page.getByPlaceholder('api.target.local/v1/profile').fill('https://outside.test/profile')
  await page.getByRole('button', { name: 'Guardar Ficha', exact: true }).click()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  const denial = page.waitForResponse(r => r.url().includes(`/reports/${id}/compile`) && r.request().method() === 'POST')
  await page.getByRole('button', { name: /Compilar Reporte/ }).click()
  const denied = await json(await denial)
  expect(denied.success).toBe(false)
  expect(denied.content).toBe('')
  await expect(page.getByTestId('report-error')).toContainText('outside.test')
  expect((await page.request.get(`/api/v1/reports/${id}/download`)).status()).toBe(409)
})
