import { test, expect } from '@playwright/test'
import { createHash } from 'node:crypto'
import { promisify } from 'node:util'
import { execFile } from 'node:child_process'
import { readFile, writeFile, rename } from 'node:fs/promises'

async function json(response) {
  expect(response.ok()).toBe(true)
  return response.json()
}

async function compile(page, id) {
  const response = page.waitForResponse(r => r.url().includes(`/reports/${id}/compile`) && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Compilar Reporte', exact: false }).first().click()
  const result = await json(await response)
  expect(result.success, result.log).toBe(true)
  return result.content
}

test('auditoría sintética: alcance, simulación, bloqueo, evidencia y reporte', async ({ page }, testInfo) => {
  test.setTimeout(90000)
  const user = JSON.parse(await readFile(new URL('../.playwright-fixture/user.json', import.meta.url), 'utf8'))
  const run = promisify(execFile)
  const { workspace, container } = JSON.parse(await readFile(new URL('../.playwright-fixture/workspace.json', import.meta.url), 'utf8'))
  const { stdout: network } = await run('docker', ['inspect', '--format', '{{.HostConfig.NetworkMode}}', container])
  expect(network.trim()).toBe('none')
  const id = 'playwright-audit'
  const title = 'Evidencia sintética de acceso a perfil'
  await page.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:4199' ? route.continue() : route.abort())
  await page.goto('/wizard')
  await page.getByLabel('Contraseña').fill(user.password)
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await page.getByPlaceholder('acme-corp', { exact: true }).fill(id)
  await page.getByPlaceholder('target.local', { exact: true }).fill('example.test')
  await page.getByRole('button', { name: 'Crear y continuar →' }).click()
  await expect(page.getByRole('button', { name: 'Guardar y continuar →' })).toBeDisabled()
  await expect(page.getByPlaceholder('target.local\n*.target.local')).toHaveValue('example.test')
  await page.getByTestId('confirm-scope').check()
  await page.getByRole('button', { name: 'Guardar y continuar →' }).click()
  const dryRun = page.getByRole('checkbox', { name: /Modo Dry-Run/ })
  await expect(dryRun).toBeChecked()
  await dryRun.uncheck()
  await expect(page.getByRole('button', { name: /Lanzar reconocimiento/ })).toBeDisabled()
  await dryRun.check()
  await page.getByRole('button', { name: /Lanzar reconocimiento/ }).click()
  await expect(page).toHaveURL(new RegExp(`/engagements/engagement/${id}$`))
  const scope = await json(await page.request.get(`/api/v1/scope/${id}`))
  expect(scope.scope.in_scope.domains).toEqual(['example.test'])
  expect(scope.authorization.allow_active).toBe(false)
  expect(scope.authorization.allow_passive).toBe(false)
  await page.getByRole('button', { name: /Reconocimiento/, exact: false }).filter({ hasText: '📡' }).click()
  await expect(page.getByText('Simulación finalizada sin consultas de red.', { exact: false })).toBeVisible({ timeout: 20000 })
  const simulated = await json(await page.request.get(`/api/v1/recon/${id}/status`))
  expect(simulated.job.status).toBe('simulated')
  expect(simulated.summary.subdomains_count).toBe(0)
  const history = page.getByTestId('recon-history')
  await expect(history.getByRole('listitem')).toHaveCount(1)
  await expect(history).toContainText(simulated.job.run_id)

  await page.getByRole('button', { name: /Alcance \(target.yaml\)/ }).click()
  await page.getByLabel('Referencia de autorización').fill('Fixture sintético Playwright; sin permiso activo')
  await page.getByLabel('Inicio', { exact: true }).fill('2020-01-01T00:00')
  await page.getByLabel('Fin', { exact: true }).fill('2099-01-01T00:00')
  const saved = page.waitForResponse(r => r.url().includes(`/scope/${id}`) && r.request().method() === 'PUT')
  await page.getByRole('button', { name: 'Guardar Alcance' }).click()
  await json(await saved)
  await page.getByRole('button', { name: /Reconocimiento/ }).filter({ hasText: '📡' }).click()
  await writeFile(`${workspace}/engagements/${id}/recon/subdomains.txt`, 'example.test\n')
  await page.locator('select').selectOption('probe')
  await page.getByLabel('Modo Dry-Run (Simulación)').uncheck()
  await page.getByRole('button', { name: 'Revisar plan sin tráfico' }).click()
  await expect(page.getByTestId('recon-preview')).toContainText('Falta permiso explícito')
  await expect(page.getByRole('button', { name: /Iniciar Reconocimiento/ })).toBeDisabled()
  await json(await page.request.post(`/api/v1/recon/${id}/run`, { data: { stage: 'probe', dry_run: false } }))
  await page.reload()
  await page.getByRole('button', { name: /Reconocimiento/ }).filter({ hasText: '📡' }).click()
  await expect(page.getByText('Reconocimiento bloqueado por Scope Guard.', { exact: true })).toBeVisible({ timeout: 20000 })
  const blocked = await json(await page.request.get(`/api/v1/recon/${id}/status`))
  expect(blocked.job.status).toBe('blocked')
  expect(blocked.job.error).toMatch(/activ/i)
  expect(blocked.job.run_id).not.toBe(simulated.job.run_id)
  await expect(history.getByRole('listitem')).toHaveCount(2)
  await page.reload()
  await page.getByRole('button', { name: /Reconocimiento/ }).filter({ hasText: '📡' }).click()
  await expect(history.getByRole('listitem')).toHaveCount(2)
  await expect(history).toContainText(simulated.job.run_id)
  await expect(history).toContainText(blocked.job.run_id)
  await expect(history).toContainText('Bloqueado (Scope Guard)')

  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await page.getByRole('button', { name: /Nueva Ficha/ }).click()
  const form = page.locator('form').filter({ has: page.getByPlaceholder('idor-user-profile, sqli-login') })
  await expect(form.locator('select').first()).toHaveValue('CANDIDATE')
  await page.getByPlaceholder('idor-user-profile, sqli-login').fill('synthetic-profile')
  await page.getByPlaceholder('api.target.local/v1/profile').fill('https://example.test/profile')
  await page.getByPlaceholder('Insecure Direct Object Reference (IDOR) en Actualización de Cuenta').fill(title)
  await page.getByPlaceholder('Explicación detallada del fallo y cómo fue detectado...').fill('Fixture sintético, no prueba sobre un objetivo real.')
  await page.getByPlaceholder('1. Realizar petición POST', { exact: false }).fill('1. Revisar la petición sintética.\n2. Comparar la respuesta y el control negativo sintéticos.')
  await page.getByPlaceholder('GET /api/user/102', { exact: false }).fill('GET /profile HTTP/1.1\nHost: example.test')
  await page.getByPlaceholder('HTTP/1.1 200 OK', { exact: false }).fill('HTTP/1.1 200 OK\nContent-Type: application/json\n\n{"fixture":true}')
  await page.getByPlaceholder('Implementar validación', { exact: false }).fill('Revisar acceso por objeto; ejemplo sintético.')
  await page.getByRole('button', { name: 'Guardar Ficha', exact: true }).click()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  const candidate = (await json(await page.request.get(`/api/v1/findings/${id}`)))[0]
  expect(candidate.frontmatter.status).toBe('CANDIDATE')
  expect(candidate.finding_id).toMatch(/^[a-f0-9]{12}4[a-f0-9]{3}[89ab][a-f0-9]{15}$/)
  await expect(page.getByTestId('finding-identity')).toContainText(candidate.finding_id)
  expect(candidate.body).toContain('Host: example.test')
  const candidateReport = await compile(page, id)
  expect(candidateReport).toContain('**0 hallazgos confirmados activos**')
  expect(candidateReport).toContain(title)
  await expect(page.locator('.report-printable div.text-center span.text-2xl')).toHaveText(['0', '0', '0', '0', '0'])
  await expect(page.locator('.report-printable')).toContainText('BORRADOR / PENDIENTE DE REVISIÓN')

  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await page.getByRole('button', { name: 'Editar', exact: true }).click()
  await expect(page.getByTestId('finding-markdown')).toHaveValue(candidate.body)
  const rejected = await page.request.post(`/api/v1/findings/${id}`, { data: { slug: candidate.slug, title, body: candidate.body, expected_source_sha256: candidate.source_sha256, status: 'PROVEN' } })
  expect(rejected.status()).toBe(409)
  await form.locator('select').first().selectOption('PROVEN')
  await expect(page.getByRole('button', { name: 'Guardar Ficha', exact: true })).toBeDisabled()
  await page.getByLabel('Ruta del artefacto', { exact: true }).fill('recon/subdomains.txt')
  await page.getByRole('button', { name: 'Revisar artefacto', exact: true }).click()
  await page.getByRole('button', { name: 'Vincular versión revisada', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Guardar Ficha', exact: true })).toBeDisabled()
  await page.getByTestId('finding-confirmation-editor').scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('confirmation-gate.png'), fullPage: true })
  await page.getByLabel('Motivo de verificación humana', { exact: true }).fill('Operador revisó el fixture sintético y su control; no acredita una prueba real.')
  await page.getByTestId('finding-markdown').fill(`${candidate.body}\n## Control negativo\nHTTP/1.1 403 Forbidden; respuesta sintética sin credencial.\n\n## Revisión\nOperador del fixture revisó petición, respuesta y control sintéticos; no acredita una prueba real.`)
  const confirmedSave = page.waitForResponse(r => r.url().includes(`/findings/${id}`) && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Guardar Ficha', exact: true }).click()
  expect((await confirmedSave).status()).toBe(200)
  await expect(form).toBeHidden()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  const confirmed = (await json(await page.request.get(`/api/v1/findings/${id}`)))[0]
  expect(confirmed.finding_id).toBe(candidate.finding_id)
  expect(confirmed.verification_rationale).toContain('Operador revisó el fixture')
  expect(confirmed.artifact_refs).toHaveLength(1)
  const confirmedReport = await compile(page, id)
  expect(confirmedReport).toContain(confirmed.verification_rationale)
  expect(confirmedReport).toContain(candidate.finding_id)
  const originalFinding = await readFile(`${workspace}/engagements/${id}/evidence/synthetic-profile.md`)
  const sourceSha = createHash('sha256').update(originalFinding).digest('hex')
  const sourceLink = page.locator('.prose-report a').filter({ hasText: 'Abrir ficha fuente' })
  await expect(sourceLink).toHaveAttribute('href', `./evidence/synthetic-profile.md#sha256=${sourceSha}`)
  await sourceLink.click()
  await expect(page.getByText('La versión actual coincide con la referencia revisada.', { exact: true })).toBeVisible()
  await expect(page.getByText(sourceSha, { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('report-finding-source.png'), fullPage: true })
  await page.getByRole('button', { name: /Reporte \(REPORT.md\)/ }).click()
  await page.locator('.prose-report a').filter({ hasText: 'recon/subdomains.txt' }).click()
  await expect(page.getByText('La versión actual coincide con la referencia revisada.', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('report-selected-artifact.png'), fullPage: true })
  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await page.reload()
  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await expect(page.getByTestId('finding-identity')).toContainText(candidate.finding_id)
  await page.screenshot({ path: testInfo.outputPath('finding-identity.png'), fullPage: true })
  const evidencePath = `${workspace}/engagements/${id}/evidence/synthetic-profile.md`
  const renamedPath = `${workspace}/engagements/${id}/evidence/renamed-profile.md`
  await rename(evidencePath, renamedPath)
  const renamedFinding = (await json(await page.request.get(`/api/v1/findings/${id}`)))[0]
  expect(renamedFinding.slug).toBe('renamed-profile')
  expect(renamedFinding.finding_id).toBe(candidate.finding_id)
  await page.reload()
  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await expect(page.getByTestId('finding-identity')).toContainText(candidate.finding_id)
  await page.screenshot({ path: testInfo.outputPath('finding-identity-renamed.png'), fullPage: true })
  await rename(renamedPath, evidencePath)

  expect(confirmedReport).toContain('**1 hallazgos confirmados activos**')
  expect(confirmedReport).toContain('HTTP/1.1 403 Forbidden')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /Empaquetar y Descargar/ }).click()
  const download = await downloadPromise
  const archive = testInfo.outputPath('synthetic-audit.tar.gz')
  await download.saveAs(archive)
  expect(await download.failure()).toBeNull()
  const { stdout: entries } = await run('tar', ['-tf', archive])
  const manifestPath = entries.split('\n').find(path => path.endsWith('/source-manifest.json'))
  expect(manifestPath).toBeTruthy()
  const { stdout: manifestText } = await run('tar', ['-xOf', archive, manifestPath])
  const manifest = JSON.parse(manifestText)
  expect(manifest.schema_version).toBe(1)
  expect(manifest.sanitized).toBe(true)
  expect(manifest.files.map(file => file.path)).toEqual(expect.arrayContaining(['REPORT.md', 'target.yaml', 'evidence/synthetic-profile.md', 'recon/subdomains.txt']))
  for (const file of manifest.files) {
    expect(file.original_sha256).toMatch(/^[a-f0-9]{64}$/)
    expect(file.export_sha256).toMatch(/^[a-f0-9]{64}$/)
    const exportedPath = entries.split('\n').find(path => path.endsWith(`/${file.path}`))
    expect(exportedPath).toBeTruthy()
    const { stdout: exported } = await run('tar', ['-xOf', archive, exportedPath], { encoding: 'buffer' })
    expect(createHash('sha256').update(exported).digest('hex')).toBe(file.export_sha256)
    const original = await readFile(`${workspace}/engagements/${id}/${file.path}`)
    expect(createHash('sha256').update(original).digest('hex')).toBe(file.original_sha256)
  }
  const findingManifestPath = entries.split('\n').find(path => path.endsWith('/finding-manifest.json'))
  expect(findingManifestPath).toBeTruthy()
  const { stdout: findingManifestText } = await run('tar', ['-xOf', archive, findingManifestPath])
  const findingManifest = JSON.parse(findingManifestText)
  expect(findingManifest.schema_version).toBe(1)
  expect(findingManifest.findings).toHaveLength(1)
  const linked = findingManifest.findings[0]
  expect(linked.finding_id).toBe(candidate.finding_id)
  expect(linked.identity_status).toBe('recorded')
  expect(linked.source).toEqual(manifest.files.find(file => file.path === 'evidence/synthetic-profile.md'))
  expect(linked.source.original_sha256).toBe(sourceSha)
  expect(linked.artifact_refs).toEqual([{ ...manifest.files.find(file => file.path === 'recon/subdomains.txt'), expected_sha256: confirmed.artifact_refs[0].sha256 }])
  expect(findingManifest.report).toEqual(manifest.files.find(file => file.path === 'REPORT.md'))
  await page.reload()
  await page.getByRole('button', { name: /Reporte \(REPORT.md\)/ }).click()
  await page.getByRole('button', { name: /Markdown/ }).click()
  await expect(page.locator('pre').filter({ hasText: '# Informe de Auditoría' })).toContainText(confirmedReport.trim())

  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await page.getByRole('button', { name: 'Editar', exact: true }).click()
  await page.getByPlaceholder('api.target.local/v1/profile').fill('https://outside.test/profile')
  const badSave = page.waitForResponse(r => r.url().includes(`/findings/${id}`) && r.request().method() === 'POST')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Guardar Ficha', exact: true }).click()
  expect((await badSave).status()).toBe(409)
  await form.locator('select').first().selectOption('CANDIDATE')
  await page.getByRole('button', { name: 'Guardar Ficha', exact: true }).click()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  const denial = page.waitForResponse(r => r.url().includes(`/reports/${id}/compile`) && r.request().method() === 'POST')
  await page.getByRole('button', { name: /Compilar Reporte/ }).click()
  const denied = await json(await denial)
  expect(denied.success).toBe(false)
  expect(denied.content).toBe('')
  await expect(page.getByTestId('report-error')).toContainText('outside.test')
  expect((await page.request.get(`/api/v1/reports/${id}/download`)).status()).toBe(409)
  const deletionSource = await json(await page.request.get(`/api/v1/findings/${id}/${candidate.slug}`))
  expect((await page.request.delete(`/api/v1/findings/${id}/${candidate.slug}?expected_source_sha256=${deletionSource.source_sha256}`)).ok()).toBe(true)
  const legacyPath = `${workspace}/engagements/${id}/evidence/legacy.md`
  const legacy = '---\ntitle: Confirmación antigua sintética\nasset: example.test\nstatus: VERIFIED\n---\n## Pasos para Reproducir\nFixture\n## Remediación\nFixture\n'
  await writeFile(legacyPath, legacy)
  await page.reload()
  await page.getByRole('button', { name: /Hallazgos \(evidence\/\)/ }).click()
  await expect(page.getByText('Revisión pendiente (VERIFIED)', { exact: true })).toBeVisible()
  expect(await readFile(legacyPath, 'utf8')).toBe(legacy)
  const legacyCompile = await json(await page.request.post(`/api/v1/reports/${id}/compile`))
  expect(legacyCompile.success).toBe(false)
  expect(legacyCompile.log).toContain('artefacto vinculado')
  expect((await page.request.get(`/api/v1/reports/${id}/download`)).status()).toBe(409)
  await page.screenshot({ path: testInfo.outputPath('legacy-review-pending.png'), fullPage: true })
})
