import { test, expect } from '@playwright/test'
import { readFile, writeFile } from 'node:fs/promises'

test('vista previa sin job y revisión obsoleta rechazada antes de simular', async ({ page }, testInfo) => {
  const user = JSON.parse(await readFile(new URL('../.playwright-fixture/user.json', import.meta.url), 'utf8'))
  const { workspace } = JSON.parse(await readFile(new URL('../.playwright-fixture/workspace.json', import.meta.url), 'utf8'))
  const id = 'preview-audit'
  await page.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:4199' ? route.continue() : route.abort())
  await page.goto('/')
  await page.getByLabel('Contraseña').fill(user.password)
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Cerrar sesión', exact: true })).toBeVisible()
  expect((await page.request.post('/api/v1/engagements', { data: { name: id, domain: 'example.test', type: 'engagement' } })).ok()).toBe(true)
  const input = `${workspace}/engagements/${id}/recon/subdomains.txt`
  await writeFile(input, 'example.test\nunknown.test\n')
  await page.goto(`/engagements/engagement/${id}`)
  await page.getByRole('button', { name: /Reconocimiento/ }).filter({ hasText: '📡' }).click()
  await page.locator('select').selectOption('probe')
  const launch = page.getByRole('button', { name: /Iniciar Reconocimiento/ })
  await expect(launch).toBeDisabled()
  await page.getByRole('button', { name: 'Revisar plan sin tráfico' }).click()
  const preview = page.getByTestId('recon-preview')
  await expect(preview).toContainText('1 targets conocidos · 1 descartados')
  await expect(preview).toContainText('unknown.test')
  await expect(preview).toContainText('Falta permiso explícito')
  await expect(launch).toBeDisabled()
  expect((await (await page.request.get(`/api/v1/recon/${id}/history`)).json()).jobs).toHaveLength(0)
  await page.getByLabel('Modo Dry-Run (Simulación)').check()
  await expect(preview).toHaveCount(0)
  await page.getByRole('button', { name: 'Revisar plan sin tráfico' }).click()
  await expect(preview).toContainText('SIMULACIÓN')
  await expect(launch).toBeEnabled()
  await writeFile(input, 'example.test\n')
  await launch.click()
  await expect(page.getByText('El plan cambió o está bloqueado;', { exact: false })).toBeVisible()
  await expect(launch).toBeDisabled()
  expect((await (await page.request.get(`/api/v1/recon/${id}/history`)).json()).jobs).toHaveLength(0)
  await page.getByRole('button', { name: 'Revisar plan sin tráfico' }).click()
  await expect(launch).toBeEnabled()
  await launch.click()
  await expect(page.getByText('Simulación finalizada sin consultas de red.', { exact: false })).toBeVisible({ timeout: 20000 })
  const history = page.getByTestId('recon-history')
  await expect(history.getByRole('listitem')).toHaveCount(1)
  const saved = (await (await page.request.get(`/api/v1/recon/${id}/history`)).json()).jobs[0]
  expect(saved.reviewed_plan.stages[0].targets).toEqual([{ host: 'example.test', verdict: 'IN_SCOPE' }])
  expect(saved.reviewed_plan.authorization.allow_active).toBe(false)
  await writeFile(input, 'changed.test\n')
  await page.reload()
  await page.getByRole('button', { name: /Reconocimiento/ }).filter({ hasText: '📡' }).click()
  await history.getByText('Plan revisado al iniciar', { exact: true }).click()
  const review = history.getByTestId('recon-history-review')
  await expect(review).toContainText(saved.reviewed_plan.plan_revision)
  await expect(review).toContainText('example.test · IN_SCOPE')
  await expect(review).toContainText('activo no')
  await expect(review).toContainText('8 s por petición')
  await expect(review).not.toContainText('changed.test')
  expect((await (await page.request.get(`/api/v1/recon/${id}/history`)).json()).jobs[0].reviewed_plan).toEqual(saved.reviewed_plan)
  await page.screenshot({ path: testInfo.outputPath('review-history.png'), fullPage: true })
})

test('scope inválido al arrancar queda bloqueado y conserva resultados anteriores', async ({ page }, testInfo) => {
  const user = JSON.parse(await readFile(new URL('../.playwright-fixture/user.json', import.meta.url), 'utf8'))
  const { workspace } = JSON.parse(await readFile(new URL('../.playwright-fixture/workspace.json', import.meta.url), 'utf8'))
  const id = 'startup-block'
  await page.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:4199' ? route.continue() : route.abort())
  await page.goto('/')
  await page.getByLabel('Contraseña').fill(user.password)
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Cerrar sesión', exact: true })).toBeVisible()
  expect((await page.request.post('/api/v1/engagements', { data: { name: id, domain: 'example.test', type: 'engagement' } })).ok()).toBe(true)
  await writeFile(`${workspace}/engagements/${id}/target.yaml`, 'scope: [invalid')
  const original = JSON.stringify({ run_id: 'previous', status: 'completed', subdomains_count: 7 })
  const summary = `${workspace}/engagements/${id}/recon/summary.json`
  await writeFile(summary, original)
  expect((await page.request.post(`/api/v1/recon/${id}/run`, { data: { stage: 'probe' } })).ok()).toBe(true)
  await page.goto(`/engagements/engagement/${id}`)
  await page.getByRole('button', { name: /Reconocimiento/ }).filter({ hasText: '📡' }).click()
  await expect(page.getByText('Reconocimiento bloqueado por Scope Guard.', { exact: true })).toBeVisible({ timeout: 20000 })
  const result = (await (await page.request.get(`/api/v1/recon/${id}/history`)).json()).jobs[0]
  expect(result.status).toBe('blocked')
  expect(result.error).not.toBe('Código de salida: 1')
  expect(await readFile(summary, 'utf8')).toBe(original)
  await page.reload()
  await page.getByRole('button', { name: /Reconocimiento/ }).filter({ hasText: '📡' }).click()
  await expect(page.getByTestId('recon-history')).toContainText(result.run_id)
  await expect(page.getByTestId('recon-history')).toContainText('Bloqueado (Scope Guard)')
  await expect(page.getByTestId('recon-history')).toContainText(result.error)
  await page.screenshot({ path: testInfo.outputPath('startup-block.png'), fullPage: true })
})
