import { test, expect } from '@playwright/test'
import { readFile, writeFile } from 'node:fs/promises'

test('vista previa sin job y revisión obsoleta rechazada antes de simular', async ({ page }) => {
  const user = JSON.parse(await readFile(new URL('../.playwright-fixture/user.json', import.meta.url), 'utf8'))
  const { workspace } = JSON.parse(await readFile(new URL('../.playwright-fixture/workspace.json', import.meta.url), 'utf8'))
  const id = 'preview-audit'
  await page.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:4199' ? route.continue() : route.abort())
  await page.goto('/')
  await page.getByLabel('Contraseña').fill(user.password)
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Cerrar sesión', exact: true })).toBeVisible()
  expect((await page.request.post('/api/v1/engagements', { data: { name: id, domain: 'example.test', type: 'engagement' } })).ok()).toBe(true)
  const input = `${workspace}/engagements/${id}/recon/subdomains.txt`
  await writeFile(input, 'example.test\nunknown.test\n')
  await page.goto(`/engagements/engagement/${id}`)
  await page.getByRole('button', { name: /Reconocimiento/ }).filter({ hasText: '📡' }).click()
  await page.locator('select').selectOption('probe')
  const launch = page.getByRole('button', { name: /Iniciar Reconocimiento/ })
  await expect(launch).toBeDisabled()
  await page.getByRole('button', { name: 'Revisar plan sin tráfico' }).click()
  const preview = page.getByTestId('recon-preview')
  await expect(preview).toContainText('1 targets conocidos · 1 descartados')
  await expect(preview).toContainText('unknown.test')
  await expect(preview).toContainText('Falta permiso explícito')
  await expect(launch).toBeDisabled()
  expect((await (await page.request.get(`/api/v1/recon/${id}/history`)).json()).jobs).toHaveLength(0)
  await page.getByLabel('Modo Dry-Run (Simulación)').check()
  await expect(preview).toHaveCount(0)
  await page.getByRole('button', { name: 'Revisar plan sin tráfico' }).click()
  await expect(preview).toContainText('SIMULACIÓN')
  await expect(launch).toBeEnabled()
  await writeFile(input, 'example.test\n')
  await launch.click()
  await expect(page.getByText('El plan cambió o está bloqueado;', { exact: false })).toBeVisible()
  await expect(launch).toBeDisabled()
  expect((await (await page.request.get(`/api/v1/recon/${id}/history`)).json()).jobs).toHaveLength(0)
  await page.getByRole('button', { name: 'Revisar plan sin tráfico' }).click()
  await expect(launch).toBeEnabled()
  await launch.click()
  await expect(page.getByText('Simulación finalizada sin consultas de red.', { exact: false })).toBeVisible({ timeout: 20000 })
  await expect(page.getByTestId('recon-history').getByRole('listitem')).toHaveCount(1)
})
